### ISSUE TITLE
Support Silex v2

### ISSUE THREAD

**Issue by Atriedes** [danadesrosiers/silex-annotation-provider#12]
It would be great if support silex v2

**Comment by danadesrosiers** [comment]
I'm planning to put out a 2.0 release to support Silex v2 when it is released.

**Comment by DerManoMann** [comment]
Any chance of setting up a 2.0 branch before that? I suppose the changes in 2.0 the code relies on should be fairly stable, so there would be time to start testing beforehand...

**Comment by danadesrosiers** [comment]
Fair enough.  I can get something started here in the near future.

**Comment by danadesrosiers** [comment]
The master branch has been updated to support Silex 2.0.
