### ISSUE TITLE
Removing controller group?

### ISSUE THREAD

**Issue by praswicaksono** [danadesrosiers/silex-annotation-provider#14]
Is there any specific reason you remove these feature?

**Comment by danadesrosiers** [comment]
The `@Controller` annotation was introduced in v1.1.  The prefix (group) can be set on that annotation.  The `@Controller` annotation will be required in v2.0, so setting the group in the 'annot.controllers' option is redundant.  I had to hack around a bit to keep backwards compatibility in v1.1.  Removing it simplifies the code and the interface, which is a major goal of mine for v2.0.  I am considering removing the 'annot.controllers' options leaving only 'annot.controllerDir', but I'm not sure yet.

**Comment by Atriedes** [comment]
Yeah thats good idea, removing annot.controllers and only require annot.controllerDir. It can save time for me at least, because I scan controller dir and register it one by one. Also it would be nice if it scan multiple directory
