### ISSUE TITLE
Dependency injection

### ISSUE THREAD

**Issue by majusko** [danadesrosiers/silex-annotation-provider#21]
I am injecting into controller some factories and library is overriding PHP-DI and injecting into controller Silex\Application. Is there any workaround about this?

**Comment by majusko** [comment]
Would you be interested in DI compatibility if I implement such feature as a pull request?

**Comment by danadesrosiers** [comment]
Silex is itself a dependency injection container, but I understand if you would rather use something else.  You should be able to accomplish what you want by overriding the 'annot.registerServiceController' function.  The default is here: https://github.com/danadesrosiers/silex-annotation-provider/blob/master/src/AnnotationServiceProvider.php#L86-L95.

**Comment by Rastusik** [comment]
@danadesrosiers : what @majusko meant was that it would be nice if there was a possibility to make this package compatible with this one: https://github.com/PHP-DI/Silex-Bridge ... we might provide a pull request if necessary ... what is your opinion about the suggestion? do you still think that there should be a third package making this integration possible?

**Comment by danadesrosiers** [comment]
There is no need to create a separate package.  Just add the following after registering the annotation provider:

```
$app['annot.registerServiceController'] = $app->protect(
   function ($controllerName) use ($app, $container) {
        $app[$controllerName] = function (Application $app) use ($container, $controllerName) {
            return $container->get($controllerName);
        };
    }
);
```

**Comment by Rastusik** [comment]
I know that there is no need, I'm just thinking that it would be nice if it wouldn't be needed to overwrite the annotation provider manually in each app. But ok, if you think that this is unneccessary, we'll just do the override or maybe provide a unifying package. Thanks for the feedback

**Comment by alcalyn** [comment]
Why not something like

``` php
/**
 * @SLX\Controller(prefix="api/articles", service="app.controllers.article")
 */
class ArticleController
```

?
