### ISSUE TITLE
Registering multiple directoris not working with Apcu Cache

### ISSUE THREAD

**Issue by ruby232** [danadesrosiers/silex-annotation-provider#22]
I work with 
Silex: v2.1.0
ddesrosiers/silex-annotation-provider: v2.0
doctrine/cache: v1.7.1
PHP: 7.1.5
Docker, FPM, Alpine

In my **src/app.php**  configure AnnotationServiceProvider
`php
$app->register(new AnnotationServiceProvider(), [
    "annot.cache" => new ApcuCache(),
    "annot.controllerDir" => [
            ROOT_PATH . "/src/App/Controllers",
            ROOT_PATH . "/src/Core/Controllers"
    ]
]);
`
And only work routes in **/src/App/Controllers**, other routes show error "Route not found".
But i remove _annot.cache_ and work fine

**Comment by danadesrosiers** [comment]
Fixed!  Thanks for reporting the issue.
