### ISSUE TITLE
Annotation exception

### ISSUE THREAD

**Issue by marabesi** [danadesrosiers/silex-annotation-provider#24]
Is there a way to remove a given route being automatically used by the annotations?

Today I've got a bunch of controllers registered in the service provider, but let's say, for whatever reason I'd like to use the route `/foo/bar` freely. How can I accomplish that?

obs: When I say freely, I mean without any annotation. Right know silex throws an exception saying 'Route not registered'.

**Comment by danadesrosiers** [comment]
If you are on an Apache server, you can use htaccess to direct different urls to different bootstrap files.  Alternatively, you could set up an error handler to re-route URI requests that were not found.  https://silex.symfony.com/doc/2.0/usage.html#error-handlers
There's nothing in Silex Annotations itself that would help in this case.

**Comment by marabesi** [comment]
@danadesrosiers tks for the tip, I will look into more details.
