### ISSUE TITLE
Ignore route

### ISSUE THREAD

**Issue by marabesi** [danadesrosiers/silex-annotation-provider#28]
Is there a way to ignore a route for a given URL?

For example, I don't want the annotation for the path:

```
http://localhost/foo
````

But at the same time I would like to have the annotations working in the root, like:

```
http://localhost
```

**Comment by danadesrosiers** [comment]
I'm not sure I understand the question.  If you have pages you want to be able to serve without using Silex, you probably need to use htaccess rules or manually route to them in your bootstrap file.

**Comment by marabesi** [comment]
I see,

But even when I try to handle them manually, some how the annotation gets trigged.

I haven't thought about htaccess, I am going to try it.

**Comment by danadesrosiers** [comment]
There's two possibilities I can think of for a location header redirect to not work.
1. The syntax is wrong in the location header.
2. There is not an exit after setting the header.  Setting the location header does not end execution of the script.

Another way is to let the Silex routing run and set up an exception handler that checks for 404s and redirects to the appropriate page.  This not be the cleanest solution IMO.

I think htaccess is the best solution.

Good luck.
